wallpaper {
    monitor = eDP-1
    path = /home/pawel/Downloads/tapeta.jpg
    fit_mode = cover
}  

wallpaper {
    monitor = DP-1
    path = /home/pawel/Downloads/tapeta.jpg
    fit_mode = cover
}
